/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*======================================*/
/*===========  INCLUDE LIB   ===========*/
#include <Std_Types.h>
#include "BIT_MATH.h"
#include "Delay_interface.h"
/*======================================*/
/*===========  INCLUDE MCAL  ===========*/
#include "GPIO_interface.h"
#include "RCC_interface.h"
#include "SPI_interface.h"
/*======================================*/
/*===========  INCLUDE HAL  ===========*/
#include "SD_MODULE_interface.h"
#include "Stepper_interface.h"
/*======================================*/

int main(void)
{
//	volatile int i = 0;

	/* Initialize System Clock */
	MRCC_vInitSystemCLK();

	/* Enable Clock for IOPBEN on APB2 bus */
	MRCC_vEnableClock(APB2 , _PERIPHERAL_EN_IOPBEN);

	/* Reset CRL Register */
	MGIO_vResetCR(_GPIOB_PORT, GPIO_PIN_3);

	/* Stepper Init */
	HAL_StepperInit();

    /* Loop forever */
	while(1)
	{
		/* Stepper Rotate */
		HAL_StepperRotateCWHalfStep();
//		for(i = 0; i < 1000000; i++){};
//		HAL_StepperRotateCWFullStep();
//		for(i = 0; i < 1000000; i++){};
//		HAL_StepperRotateCWHalfStep();
	}
}
