/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*======================================*/
/*===========  INCLUDE LIB   ===========*/
#include <Std_Types.h>
#include "BIT_MATH.h"
#include "Delay_interface.h"
/*======================================*/
/*===========  INCLUDE MCAL  ===========*/
#include "GPIO_interface.h"
#include "RCC_interface.h"
#include "SPI_interface.h"
/*======================================*/
/*===========  INCLUDE HAL  ===========*/
#include "SD_MODULE_interface.h"
#include "Stepper_interface.h"
#include "LCD_interface.h"
/*======================================*/

int main(void)
{
	/* Local declarations */
	u8 L_u8Name1[] = {"Hussein"};
	u8 L_u8Name2[] = {"Mohamed"};

	/* Initialize system clock */
	MRCC_vInitSystemCLK();

	/* Enable clock for IOPBEN on APB2 bus */
	MRCC_vEnableClock(APB2 , _PERIPHERAL_EN_IOPAEN);
	MRCC_vEnableClock(APB2 , _PERIPHERAL_EN_IOPBEN);

	/* Reset CRL & CRH registers */
	MGIO_vResetCR(_GPIOA_PORT);
	MGIO_vResetCR(_GPIOB_PORT);


	/* LCD init */
	HAL_LCD_Void_LcdInit();

	/* Stepper Init */
	HAL_StepperInit();




    /* Loop forever */
	while(1)
	{
		/* Write string */
		HAL_LCD_Void_LcdWriteString(L_u8Name1);
		HAL_LCD_Void_LcdGoTo(1, 0);
		HAL_LCD_Void_LcdWriteString(L_u8Name2);

		/* Stepper Rotate */
		HAL_StepperRotateCWHalfStep();
	}
}
